opentok/opentok-meet

public/js/controllers.js
tests/unit/controllersSpec.js

Otherwise when hoolock doesn't set the simulcast property we were assuming it is set to false but in meet it is still true.

Modify let hoolock control simulcast enabled/disabled completelly

---

public/css/main.css
src/js/directives.js
src/js/simulcast-service.js
src/js/subscriber-stats.js
tests/e2e/scenarios.js
tests/protractor.conf.js
tests/unit/directivesSpec.js
tests/unit/subscriberStatsSpec.js

1. Adds frame rate to subscriber stats via new `Subscriber.getStats()` property
2. Changes the behaviour of the Restrict Framerate button to toggle through multiple frame rates (15, 7, 1, unrestricted). It uses `Subscriber.setPreferredFrameRate()` for 15fps and 7fps, and `Subscriber.restrictFrameRate()` for 1fps.
3. Makes protractor config file determine the app port and protocol dynamically, rather than use hard coded value
*Subscriber Stats: Frame Rate*
1. Run meet app with it pointing to a version of `opentok.js` that has `video.frameRate` implemented in `Subscriber.getStats()`
2. Open the same room in two browser windows
3. Click stats button in top left
4. Confirm it contains something similar to `Frame Rate: 30 fps`
*Restrict Frame Rate Button*
1. Run meet app
2. Open the same room …

Subscriber preferred framerate

---

tests/e2e/scenarios.js

I keep getting failures with:
Expected 0.8888888888888888 to equal 1.7777777777777777.
https://travis-ci.org/opentok/opentok-meet/jobs/160944386

Disabling this test for now. It's really unreliable

---

src/js/audio-acquisition-problem.js
tests/e2e/roomScenarios.js
tests/unit/audioAcquisitionProblemSpec.js

Now that we are displaying publish errors and the audio acquisition problem is just a publish error

Removing the audio-acquisition-problem alert

---

src/js/controllers.js
tests/unit/controllersSpec.js
views/room.ejs
views/screen.ejs
views/whiteboard.ejs

Replace call to `OT._.enableExperimentalErrorReporting` with `OTProperties.enableErrorReporting` setting.

OPENTOK-31614 - Enable error reporting using OTProperties instead of private method

---

package.json
src/js/h264/modify-sdp.js

We made a change in opentok.js that deprioritised H.264 for Edge. This broke our brittle sdp replacement function. I'm now using a slightly more resilient RegExp.
Make sure that H.264 works for Chrome 56.

Fix h264 in Chrome 56

---

.travis.yml
tests/e2e/h264Scenarios.js

Right now Rumor is stripping out H.264 for Mantis sessions so we need to use P2P.

Use p2p session for the H.264 test

---

src/js/safari-electron-redirect.js

Prevents redirection to `/electron/download` if `RTCPeerConnection` is defined.
[OPENTOK-33313](https://tokbox.atlassian.net/browse/OPENTOK-33313)

Don't redirect to electron if RTCPeerConn present

---

README.md
electron/app/main.js

Fixes the issue @donaltoomey found where rooms failed to load by removing electron's proxy/redirect of meet:// urls and just uses https://. (meet:// urls in safari still work.)
Build the app and check rooms load and meet://home/roomy-mcroomface in safari opens the app.
(Here's the one I built: https://files.slack.com/files-pri/T029F8997-F4MQ2V67L/download/meet-electron.dmg)
N/A

Remove electron meet protocol redirect

---

src/js/h264/modify-sdp.js
src/js/h264/useH264Only.js

Locates H264 in sdp and updates it to only include that, rather than just reordering the m line numbers to change priority.
Search 'sdpTransforms' in the console when publishing and check that only H264 is present in the modified local offer.
[OPENTOK-33695](https://tokbox.atlassian.net/browse/OPENTOK-33695) (this PR helps but does NOT resolve the ticket)

Change sdp to *only* have h264 when h264 flag is on

---

server/routes.js
views/room.ejs

meet.tokbox.com works with iOS11 so let's not forward users to install the iOS app anymore.
Join a room on iOS 11 and make sure it works.

Don't forward people to the iOS app anymore

---

src/js/directives.js

Dispatch otLayout asynchronously so there is enough time for the view to update. The issue was that we were updating the layout before the DOM had changed so you had to double click twice to get it to work and then if someone new joined or the DOM updated for any other reason then it would redraw and things would be out of sync.
Open 3 tabs so you're subscribing to 2 participants. Double click on one of the participants (or click the expand button) and make sure that the video expands as expected.

 Fix wonky expand bug

---

src/js/controllers.js
tests/unit/controllersSpec.js

Enable stereo for HD publishers
Publish and make sure enableStereo is being passed to the Publisher.
OPENTOK-37443

OPENTOK-37443 - Enable stereo for HD publishers

---

src/js/subscriber-stats.js
tests/unit/subscriberStatsSpec.js

Keep listening to 'qos' events because the codec can change now.

OPENTOK-36090 - Let the video codec refresh

---

src/js/controllers.js
tests/unit/controllersSpec.js

Adds `_allowSafariSimulcast` flag to the publisher props so that, when implemented in opentok.js, safari will be added to the whitelist
webrtc-js PR: https://github.com/opentok/webrtc-js/pull/2858
Set a breakpoint at the start of initPublisher and check that the `options` variable contains `{ _allowSafariSimulcast: true }`.
[OPENTOK-38176](https://tokbox.atlassian.net/browse/OPENTOK-38176)

OPENTOK-38176: Use _allowSafariSimulcast flag

---

src/js/controllers.js
tests/unit/controllersSpec.js

disabling stereo as aec is not supported for it by Chrome
use meet and see there is no echo
https://tokbox.atlassian.net/browse/OPENTOK-38959

fix aec removing stereo [OPENTOK-38959]

---

.travis.yml
src/js/publisher-stats.js
src/js/subscriber-stats.js
src/templates/publisher-stats.html
src/templates/subscriber-stats.html

Add streamId to widget stats
When publishing, StreamId field should be present on the bottom of the publisher stats widget.
When subscribing, StreamId field should be present above the origin server field in the subscriber stats widget
n/a

Add streamId to widget stats

---

plugins/archiving/stylesheet.js

Modifying the css for the archive. It is up to 16 videos. Screenshare comes first.
A sample test case could be:
- 2 camera publishers
- Start archive.
- Screen share.
- Stop screen share.
- Add 3 camera publishers.
- Start 2 screen share.
- Stop archive.
**Expected result: archive must contain:**
- 2 videos at the beginning. (50% width each)
- Only one screen share. (100% width)
- Again 2 videos. (50% width each)
- Then 5 videos. (33% width and height each, i.e. 3x3 grid,  4 black screens to complete the grid)
- And finally only 2 screenshare (no camera video present)

Updating archive layout to optimise screen share

---

README.md
package.json

Adding local setup instructions to readme for running the app locally.
Formatted readme can be viewed on the branch: https://github.com/maikthomas/opentok-meet/tree/readme-local-setup
You could follow the steps I added to the readme and try to run to the app.
There is no ticket for this.

Add local setup instructions for README

---

plugins/screen/index.js
plugins/whiteboard/index.js
public/css/main.css
server/routes.js
src/js/controllers.js
src/js/directives.js
src/js/login/controller.js
src/js/services.js
tests/unit/login/controllerSpec.js
tests/unit/servicesSpec.js
views/index.ejs
views/room.ejs
views/screen.ejs
views/whiteboard.ejs

This PR adds force mute functionality to opentok-meet. Also, adds option to select between different roles (**Note**: default role for user in opentok-meet is set to `publisher`. Force mute functionality can be accessed only by a user with `moderator` role priviledges)
- Get the changes from this branch https://github.com/opentok/webrtc-js/pull/3323. Build and run the project using the command `npm start`
- Get the opentok.js from http://localhost:3000/opentok.js. Copy the opentok.js to public/js folder
- Start the redis-server
- Start opentok-meet by running the command - `npm install && npm postinstall && npm start`
- Launch opentok-meet in a browser. Join session as a moderator
- Join the same session through multiple tabs (token role can be anything)
- `Mute All except publisher` …

OPENTOK-42849: Add force mute buttons to meet

---

plugins/archiving/stylesheet.js

This PR adds grid centering to the custom layout used by meet for archiving
Do an archive with at least 3 cameras (or 3 screens) and validate that the third stream is centred horizontally in the bottom row
https://jira.vonage.com/browse/OPENTOK-43671

Add grid centering to custom layout. [OPENTOK-43671]

---

server/routes.js
src/js/isValidTokenRole.js
src/js/login/controller.js
tests/unit/index.js
tests/unit/isValidTokenRoleSpec.js
tests/unit/login/controllerSpec.js

Checks for invalid token role.  If valid, a default is assumed.
Confirm that invalid token roles can cause meet to crash
* Checkout `master` branch
* Build and run meet
* Open http://localhost:3000/testing-if-meet-crashes?tokenRole=moderators
* Notice that meet crashes
Confirm that invalid token role no longer causes meet to crash
* Checkout this branch
* Build and run meet
* Open http://localhost:3000/testing-if-meet-crashes?tokenRole=moderators
* Notice that meet doesn't crash
https://jira.vonage.com/browse/OPENTOK-43815

OPENTOK-43815: Check for invalid token role

---

package-lock.json
package.json
src/js/helpers/analytics.js
src/js/helpers/publisher-rtt-watcher.js
src/js/publisher-stats.js
src/js/webview-controller.js

This PR adds a watcher to the publisher so that we can detect when we have really high values of rtt (=> 10000) either for video or audio.
Will be hard to test since we can't reproduce the scenario. But, we can make a change to see how it will log:
- Change the line 32 in the file `publisher-rtt-watcher.js` to this:
```
if (roundTripTime <= RTT_THRESHOLD) {
```
- npm run build
- npm start
- Open localhost:3000 and join a room
- go to network tab and check that every 30s you should see a new ClientEvent log with a data similar to this:
```
clientSystemTime: 1629925770740
clientVersion: "v2.20.3"
componentId: "meet.tokbox.com"
connectionId: "90c76575-2007-4d5b-b4b7-b6cd533747c1"
guid: "2c8e322b-0feb-4b6d-859d-2bed9ea98dbb"
kind: "video"
logVersion: "2"
name: "meet.tokbox.com"
partnerId: …
```

[OPENTOK-43733] Log when RTT is really high

---

src/js/controllers.js
src/js/login/controller.js
tests/e2e/dtxScenarios.js

JS SDK recently added support for Opus DTX.  This PR updates meet so that is uses DTX by default.
A meet session can be created via url or via login page. For both cases DTX should be enabled by default. 
e2e tests for dtxScenarios has been updated as well.
_**Creating a session via login page**_ 
1. Run the app and make sure you're on the login page. Click on _advanced_ and view that the DTX checkbox is checked by default. 
2. Enter a room name and enter the session. Check to make sure DTX is enabled by opening the console and under _All levels_, select _Verbose_. Search for **_'usedtx'_** and see that it appears in the console. 
_**Creating a session via url**_ 
3. Create a session via url without specifying DTX configuration. For example: _http://localhost:3000/testing_
4. DTX should …

OPENTOK-44945: Meet should use DTX as a default

---

src/js/controllers.js
views/room.ejs

This PR is adding **enableMuteOnEntry** and **disableMuteOnEntry** buttons in meet.
**Testing with 3 users** 
1. On the login page, create a room and make sure you are a moderator 
2. In the room, select the **Enable Mute On Entry** button and make sure you (moderator) are not muted
3. Join the room as another user as any other role, and make sure you are muted. 
4. Go back to the original moderator tab and select the  **Disable Mute On Entry** button
5. Go back to the tab of the other user and make sure you are still muted (Disable Mute On Entry will not unmute users that are currently muted)
6. Join the room as another user as any other role, and make sure you are not muted
Note: the Mic button on the bottom row of buttons does get updated with 'Enable Mute On Entry'. To check to see if …

OPENTOK-44484: Make force mute buttons in meet so that it can enable and disable

---

package-lock.json
package.json

npm install was broken by git:// protocol used in dependency. 
I changed it to https:// in this repo
https://github.com/maikthomas/opentok-editor/commit/e572ab56c5353378bb14ef90f08b6a3d8958b3be
and then used that commit for our opentok-editor dependency in meet.
- Checkout locally and run `npm install`
- ensure it works
OPENTOK-47128

OPENTOK-47128 Fix npm build by removing git:// dependency
