views/room.ejs
@aullman you don't really want to know what this does. Happy to explain it if you want :-)
cc @ggarber
=> snoop on meet.tokbox.com

views/room.ejs
Reapplying #9 with latest changes to master.
=> Fippo snoop

.gitignore, .tern-project, .travis.yml, bower.json, package.json, public/css/main.css, public/js/controllers.js, public/js/screen/directive.js, server/routes.js, tests/e2e/scenarios.js, tests/firefox-helper.js, tests/protractor.conf.js, tests/unit/screen/directiveSpec.js, views/room.ejs, views/whiteboard.ejs
Including whiteboard smoothing and testing in Firefox using travis-multirunner instead of browserstack.
=> Merging in changes from master

src/js/controllers.js, tests/unit/controllersSpec.js
This reverts commit 8cddba20b6dc3fd13b7fe52dd1464ce186717723.
=> Bringing back stream prioritisation

tests/e2e/scenarios.js
Wait 1 second before clicking archive button. For some reason the archive light doesn't show up sometimes if I click it too soon.
=> Wait 1 second before clicking archive button

app.js, package.json, server/anvil.js, server/roomstore.js, server/routes.js, src/js/subscriber-stats.js, tests/e2e/scenarios.js
Subscriber Stats gets for each subscriber the edge server and the origin server
=> Subscriber Stats reports origin and edge server

public/css/index.css, src/js/app.js, src/js/controllers.js, src/js/login/controller.js, src/js/notifications.js, tests/e2e/loginScenarios.js, tests/unit/index.js, tests/unit/login/controllerSpec.js, tests/unit/notificationsSpec.js, views/index.ejs, views/room.ejs
There are some bug fixes and new features added recently.
=> Merge master branch

package.json, src/css/audio-acquisition-problem.css, src/js/app.js, src/js/audio-acquisition-problem.js, tests/e2e/roomScenarios.js, tests/unit/audioAcquisitionProblemSpec.js, tests/unit/index.js, tests/unit/subscriberStatsSpec.js, views/room.ejs
Display an alert message when we get an 'audioAcquisitionProblem' event from the Publisher. This detects [this Chrome issue](https://bugs.chromium.org/p/webrtc/issues/detail?id=4799) using [this workaround](https://medium.com/the-making-of-appear-in/working-around-webrtc-bugs-d4f6fdb763f#.ia8y7b2kk).
=> Show an alert when we get an 'audioAcquisitionProblem'

public/css/main.css, src/css/subscriber-report.css, src/js/app.js, src/js/subscriber-report.js, tests/e2e/2browserScenarios.js, tests/unit/subscriberReportSpec.js, views/room.ejs
=> Add quality report

package.json, public/css/main.css, src/js/app.js, src/js/controllers.js, src/js/login/app.js, src/js/whiteboard/app.js, tests/e2e/textchatScenarios.js, tests/karma.conf.js, views/room.ejs, webpack.config.js
Adding textchat to meet.tokbox.com
There is a textchat button now in meet, click it and play with text chat.
=> Add Textchat to meet

src/js/safari-electron-redirect.js
See https://github.com/opentok/opentok-meet/pull/47
=> Don't redirect to electron if RTCPeerConn present

src/js/h264/modify-sdp.js, src/js/h264/useH264Only.js
Submitting PR again from the same repo. See https://github.com/opentok/opentok-meet/pull/51
=> Change sdp to *only* have h264 when h264 flag is on

views/room.ejs
@anarchyco seems to have shutdown the server this is expecting to run against
=> :wave: rtcstats

.travis.yml, package-lock.json, package.json, public/css/main.css, src/css/publisher-stats.css, src/js/app.js, src/js/controllers.js, src/js/publisher-stats.js, src/js/subscriber-stats.js, src/templates/publisher-stats.html, src/templates/subscriber-stats.html, tests/e2e/2browserScenarios.js, tests/e2e/h264Scenarios.js, tests/e2e/roomScenarios.js, tests/karma.conf.js, tests/unit/subscriberStatsSpec.js, views/room.ejs, webpack.config.js
Merging https://github.com/aullman/opentok-meet/pull/194
OPENTOK-35598
=> OPENTOK-35598 - Merge publisher stats

src/css/microphone-picker.css, src/js/app.js, src/js/microphone-picker.js, src/templates/microphone-picker.html, tests/unit/index.js, tests/unit/microphonePickerSpec.js, views/room.ejs
Adding a microphone picker to the Publisher. See image.
Publish on a machine that has more than 1 microphone and make sure that you can switch between the microphones.
OPENTOK-37632
=>  OPENTOK-37632 - Adding microphone picker

package-lock.json, package.json
Update to newer opentok-whiteboard that has a fix for capture functionality
Try using the capture button in the whiteboard in Chrome and make sure it downloads and image.
=> Update to newer opentok-whiteboard that has a fix for capture functionality

src/js/subscriber-stats.js
See https://github.com/opentok/opentok-meet/pull/72 for more details
=> OPENTOK-37942 Fix meet not showing codec information

package-lock.json, package.json, server/roomstore.js, src/css/cycle-camera.css, src/css/filter-picker.css, src/js/app.js, src/js/controllers.js, src/js/filter-picker.js, src/js/filtered-publisher.js, src/templates/filter-picker.html, tests/e2e/roomScenarios.js, tests/firefox-helper.js, tests/unit/controllersSpec.js, tests/unit/notificationsSpec.js, views/room.ejs, webpack.config.js
Adding a filter picker using opentok-camera-filters
=>  Adding a filter picker using opentok-camera-filters

src/js/notifications.js, tests/unit/notificationsSpec.js
Cherry-picking over https://github.com/aullman/opentok-meet/pull/219
=> Notification visibility

src/js/controllers.js, tests/unit/controllersSpec.js
Submitting PR from the same repo so that our encrypted variables in Travis work. See https://github.com/opentok/opentok-meet/pull/75 for details
=> Opentok 38176

src/js/lib/error-reporting.js
Expands what Sentry understands to be parts of our application. Which should improve their finger-printing and error duplication detection.
1. Run
2. Create an error
3. Observe it lands in Sentry
Once merged, observe Sentry for the next week and ensure errors are being picked up, and there are less duplicates.
=> OPENTOK-38893 Improve error matching in Sentry

package-lock.json, server/routes.js
Adding set layout class list endpoint.
You should be able to hit `{room}/{streamId}?layoutClassList=focus` and get a response where stream class list array contains value "focus".
=> Add set layout class list endpoint

views/index.ejs
The old link was dead. I've replaced with the working one
Replacing the old knowledgbase link with a new one
Navigate to https://support.tokbox.com/hc/en-us/articles/360029411712-What-is-the-difference-between-a-Routed-vs-Relayed-Session-
N/A
=> Updating Knowledgbase link

src/js/filtered-publisher.js
=> changed publisher resolution to qvga

package-lock.json, package.json
=> updated dependcy

package-lock.json, package.json
=> Scale resolution

package.json
=> Switch to a branch of angular with audio muted

config.json.sample, package-lock.json, package.json
=> updated opentok angular to have video and audio false

config.json.sample, package-lock.json, package.json
=> updating angular module to use no video and muted audiop

config.json.sample, package-lock.json, package.json
=> updated package-lock

package-lock.json, package.json
=> Only one subscriber at a time with no auido or video

package-lock.json, package.json, src/js/controllers.js, views/room.ejs
=> no longer creates an ot-layout for non subscribers

.gitignore, src/js/controllers.js, views/room.ejs
Create a branch of meet where only one user is subscribing and all publishers are sending QQQVGA
=> Scale down QVGA resolution by 4 

package-lock.json, package.json
Updating opentok-angular dep in order to force TURN on meet for Next-Gen TURN deep test.
Check transportPolicy is `relay` and no STUN server present in iceServers list.
https://jira.vonage.com/browse/OPENTOK-43696
=> [OPENTOK-43696] Force TURN on meet for Next-Gen TURN deep test

plugins/archiving/index.js, plugins/phone/index.js, plugins/subscriber-info/index.js, plugins/webviewcomposer/index.js, server/roomstore.js, server/routes.js
=> [OPENTOK-43154] Bug fix for allowing no-auth when no client id

server/roomstore.js
=> [OPENTOK-43154] Define empty req
